name: CI for Dockerized Node.js App

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t app .

      # Step 4: Run the Docker container
      - name: Run Docker container
        run: |
          docker run -d -p 3000:3000 app

      # Step 5: Test the application
      - name: Test Hello World endpoint
        run: |
          sleep 5 # Wait for the server to start
          curl http://localhost:3000
